# Generated by Django 5.0.1 on 2024-02-03 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blog_profil_project_delete_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 3)),
        ),
    ]
